### ISSUE TITLE
what license should apply here?

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-Projects#1]
I'm thinking CC?

**Comment by kelpisland** [comment]
Yes - I think CC is the right choice, I'll apply it.

**Comment by kelpisland** [comment]
Actually, now that I'm looking at the repo -  it's falling into a bit of the grey area. The "test" I've been working with is, repo's that are meant to be human read, watched or listened to like doc's wiki's, multi media fall under CC. If it's primary focus is machine readable code then it's Apache 2. This repo's purpose is the yml file to drive the project page, seems to me that's more on the code side - thoughts?

**Comment by GregTurner** [comment]
It's 95% content, and 5% syntax/config. CC seems right.

**Comment by kelpisland** [comment]
CC it is - I'll make the changes to the repo
